# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd2c6f3f2adf28f68091f7e75cc434c771415235459ea4de9836d663141f2128566f2566d17d272321de138d112b706003f4d68ad06d5ff9c7103fb318243694

test:
  secret_key_base: ab2ebd647936f67068ee7d73e0416f5bae54fad8c3bec7104c502bee0897552d18df9c32ed35c80d38f3785ca9356ad10fbb8f22fd51ed54284c19628f906f3d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
